---
- name: Instalacion de Nginx y mostrar pagina personalizada
  hosts: all
  become: yes

  roles:
    - roles/devops
    - roles/firewall
    - roles/nginx # Esto aplicará todas las tareas definidas en roles/{devops,firewall,nginx}/tasks/main.yml
